In [9]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])


In [16]:
# 1 
arr = arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# 2
print(arr.shape)

(3, 3)


In [18]:
# 3
print(arr.size)

9


In [20]:
# 4
print(arr.ndim)

2


In [21]:
# 5
print(arr.dtype)

int32


In [22]:
# 6
print(arr.data)

In [25]:
# 7
arr2 = np.arange(9)
print(arr2)

[0 1 2 3 4 5 6 7 8]


In [28]:
# 8
arr2 = arr2.reshape(3,3)
print(arr+arr2)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [29]:
# 9
print(arr-arr2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [30]:
# 10
print(arr*arr2)

[[ 0  2  6]
 [12 20 30]
 [42 56 72]]


In [32]:
# 11
print(arr@arr2)

[[ 24  30  36]
 [ 51  66  81]
 [ 78 102 126]]


In [33]:
# 12
print(arr.dot(arr2))

[[ 24  30  36]
 [ 51  66  81]
 [ 78 102 126]]


In [34]:
# 13
print(arr.sum(axis=0))

[12 15 18]


In [36]:
# 14
print(arr.sum(axis=1))

[ 6 15 24]


In [41]:
# 15
print(np.maximum(arr,arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
# 16
print(np.transpose(arr))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
# 17
print(np.nonzero(arr))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [46]:
# 18
print(np.average(arr))

5.0


In [48]:
# 19
print(np.ceil(arr))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [49]:
# 20
print(np.floor(arr))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [50]:
# 21
print(np.mean(arr))

5.0


In [51]:
# 22
print(np.median(arr))

5.0


In [53]:
# 23
print(np.min(arr))

1


In [54]:
# 24
print(np.max(arr))

9


In [55]:
# 25
print(np.min(arr))

1


In [57]:
# 26
print(np.outer(arr,arr2))

[[ 0  1  2  3  4  5  6  7  8]
 [ 0  2  4  6  8 10 12 14 16]
 [ 0  3  6  9 12 15 18 21 24]
 [ 0  4  8 12 16 20 24 28 32]
 [ 0  5 10 15 20 25 30 35 40]
 [ 0  6 12 18 24 30 36 42 48]
 [ 0  7 14 21 28 35 42 49 56]
 [ 0  8 16 24 32 40 48 56 64]
 [ 0  9 18 27 36 45 54 63 72]]


In [58]:
# 27
print(np.inner(arr,arr2))

[[  8  26  44]
 [ 17  62 107]
 [ 26  98 170]]


In [60]:
# 28
print(np.nonzero(arr))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [63]:
# 29
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [64]:
# 30
print(np.trace(arr))

15


In [65]:
# 31
print(np.sort(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
# 32
print(np.argsort(arr))

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [67]:
# 33
print(np.lexsort(arr))

[0 1 2]


In [79]:
# 34
print(np.flip(arr))

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [81]:
# 35
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [83]:
# 36
print(arr.ravel())

[1 2 3 4 5 6 7 8 9]


In [84]:
# 37
print(np.tan(arr))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [85]:
# 38
print(np.radians(arr))

[[0.01745329 0.03490659 0.05235988]
 [0.06981317 0.08726646 0.10471976]
 [0.12217305 0.13962634 0.15707963]]


In [89]:
# 39
arr=arr*1.4
print(arr)
print(np.rint(arr))

[[ 1.4  2.8  4.2]
 [ 5.6  7.   8.4]
 [ 9.8 11.2 12.6]]
[[ 1.  3.  4.]
 [ 6.  7.  8.]
 [10. 11. 13.]]


In [92]:
# 40
print(np.multiply(arr,arr2))

[[  0.    2.8   8.4]
 [ 16.8  28.   42. ]
 [ 58.8  78.4 100.8]]


In [94]:
# 41
print(np.subtract(arr,arr2))

[[1.4 1.8 2.2]
 [2.6 3.  3.4]
 [3.8 4.2 4.6]]


In [98]:
# 42
print(np.sqrt(arr2))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [103]:
# 43
print(np.reciprocal(arr))

[[0.71428571 0.35714286 0.23809524]
 [0.17857143 0.14285714 0.11904762]
 [0.10204082 0.08928571 0.07936508]]


In [104]:
# 44
print(np.negative(arr2))

[[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]]


In [105]:
# 45
print(np.zeros_like(arr2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [111]:
# 46
print(np.empty([2,2]))

[[1. 0.]
 [0. 1.]]


In [113]:
# 47
print(np.copy(arr))

[[ 1.4  2.8  4.2]
 [ 5.6  7.   8.4]
 [ 9.8 11.2 12.6]]


In [115]:
# 48
a = ["ZAIN", "Muhammad"]
print(np.char.lower(a))

['zain' 'muhammad']


In [117]:
# 49
a = ["ZAIN", "Muhammad"]
print(np.char.upper(a))

['ZAIN' 'MUHAMMAD']


In [119]:
# 50
b = ["This is the last function"]
print(np.char.split(b))

[list(['This', 'is', 'the', 'last', 'function'])]
